version: '3.9'


services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: nhan
      MONGO_INITDB_ROOT_PASSWORD: passwordkey

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: nhan
      ME_CONFIG_MONGODB_ADMINPASSWORD: passwordkey
      ME_CONFIG_MONGODB_URL: mongodb://nhan:passwordkey@mongo:27017
